kubernetesClusterDomain: cluster.local
sampleApp:
  replicas: 2
  sampleAppContainer:
    image:
      repository: weaveworksdemos/front-end
      tag: latest
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
service:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8079
  type: LoadBalancer
