apiVersion: v1
kind: Service
metadata:
  name: {{ include "pep-app.fullname" . }}-service
  labels:
  {{- include "pep-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: sample-app
  {{- include "pep-app.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.service.ports | toYaml | nindent 2 -}}